name: "Docker Actions"

on: [push]

jobs:
  action:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v1

      - name: "hello-action"
        uses: ./.github/actions/hello-world
        with:
          firstGreeting: "FIRST CUSTOM NAME"
          secondGreeting: "FIRST CUSTOM NAME"
          thirdGreeting: "FIRST CUSTOM NAME"
